plugins {
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'dev.citiescraft.bridge.BridgeServer'
}

distributions {
    main {
        contents {
            from('README.md') {
                into 'docs'
            }
            from("$rootDir/docs") {
                into 'docs'
            }
            from("$rootDir/config/citiescraft.properties") {
                into 'config'
            }
        }
    }
}
